# Generated by Django 3.0 on 2019-12-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('reg_time', models.DateTimeField(auto_now=True, null=True)),
                ('alipay_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qq_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wx_user_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 't_user_friend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('birth', models.DateField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('realname', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名')),
                ('users', models.ManyToManyField(to='user.User')),
            ],
            options={
                'db_table': 't_role',
            },
        ),
    ]
