# Generated by Django 3.0 on 2019-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='t_role_user', null=True, to='user.User'),
        ),
    ]
